name: Create hosts files of EasyPrivacy list from firebog.net

on:
  schedule:
    - cron:  '*/5 * * * *'

defaults:
  run:
    working-directory: ./easyprivacy

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create dist directory
      run: |
        mkdir -p dist
    - name: Download hosts file
      run: |
        wget -O dist/hosts https://v.firebog.net/hosts/Easyprivacy.txt
        sed -i '/^[[:space:]]*$\|^#/d' dist/hosts
    - name: Create ipv4 hosts file
      run: |
        sed -e 's/^/0.0.0.0 /' dist/hosts > dist/hosts-v4
    - name: Commit changes
      uses: EndBug/add-and-commit@v5.3.0
      with:
        author_name: Marcus Husar
        author_email: marcus.husar@gmail.com
        message: 'Update hosts files of EasyPrivacy from firebog.net.'
        add: 'easyprivacy/dist'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
